/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.demo.io.daemon.xml -p copymoveservice_interface
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef COPYMOVESERVICE_INTERFACE_H
#define COPYMOVESERVICE_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.demo.io.daemon.CopyMoveService
 */
class ComDemoIoDaemonCopyMoveServiceInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.demo.io.daemon.CopyMoveService"; }

public:
    ComDemoIoDaemonCopyMoveServiceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~ComDemoIoDaemonCopyMoveServiceInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Copy(const QString &src, const QString &dest)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(src) << QVariant::fromValue(dest);
        return asyncCallWithArgumentList(QStringLiteral("Copy"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace demo {
    namespace io {
      namespace daemon {
        typedef ::ComDemoIoDaemonCopyMoveServiceInterface CopyMoveService;
      }
    }
  }
}
#endif
