/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.demo.plugins.daemon.xml -i plugintestservice.h -a plugintestadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "plugintestadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PluginTestServiceAdaptor
 */

PluginTestServiceAdaptor::PluginTestServiceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PluginTestServiceAdaptor::~PluginTestServiceAdaptor()
{
    // destructor
}

void PluginTestServiceAdaptor::doSomething()
{
    // handle method call com.demo.plugins.daemon.PluginTestService.doSomething
    QMetaObject::invokeMethod(parent(), "doSomething");
}

