/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.demo.io.daemon.xml -i copymoveservice.h -a copymoveadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "copymoveadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CopyMoveServiceAdaptor
 */

CopyMoveServiceAdaptor::CopyMoveServiceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CopyMoveServiceAdaptor::~CopyMoveServiceAdaptor()
{
    // destructor
}

void CopyMoveServiceAdaptor::Copy(const QString &src, const QString &dest)
{
    // handle method call com.demo.io.daemon.CopyMoveService.Copy
    QMetaObject::invokeMethod(parent(), "Copy", Q_ARG(QString, src), Q_ARG(QString, dest));
}

