/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.demo.filemanager.daemon.xml -i rootservice.h -a rootadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ROOTADAPTOR_H
#define ROOTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "rootservice.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.demo.filemanager.daemon.RootService
 */
class RootServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.demo.filemanager.daemon.RootService")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.demo.filemanager.daemon.RootService\">\n"
"    <method name=\"createFileInAnyWhere\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filePath\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    RootServiceAdaptor(QObject *parent);
    virtual ~RootServiceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool createFileInAnyWhere(const QString &filePath);
Q_SIGNALS: // SIGNALS
};

#endif
